version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "phonebook_flask"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0455"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  phonebook:
    container_name: phonebook
    build: .
    links:
      - postgres:dbserver
    environment:
      SECRET_KEY: "my-secret-key"
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:0455@dbserver/phonebook_flask"
    ports:
      - 8000:5000
    volumes:
      - .:/app:ro

